export const GET_STATS = 'GET_STATS';
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';
export const GET_STATS_FAILURE = 'GET_STATS_FAILURE';

export const GET_LINKS = 'GET_LINKS';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';

export const GET_OVERLAYS = 'GET_OVERLAYS';
export const GET_OVERLAYS_SUCCESS = 'GET_OVERLAYS_SUCCESS';
export const GET_OVERLAYS_FAILURE = 'GET_OVERLAYS_FAILURE';

export const GET_USAGE = 'GET_USAGE';
export const GET_USAGE_SUCCESS = 'GET_USAGE_SUCCESS';
export const GET_USAGE_FAILURE = 'GET_USAGE_FAILURE';
