export const FETCH_OVERLAYS = 'FETCH_OVERLAYS';
export const ON_FETCH_OVERLAYS_SUCCESS = 'ON_FETCH_OVERLAYS_SUCCESS';
export const TYPE_SELECTED = 'TYPE_SELECTED';
export const CATEGORY_SELECTED = 'CATEGORY_SELECTED';
export const TEMPLATE_SELECTED = 'TEMPLATE_SELECTED';
export const NAME_SELECTED = 'NAME_SELECTED';