export const GET_ACCOUNT_DETAILS = 'GET_ACCOUNT_DETAILS';
export const GET_ACCOUNT_DETAILS_SUCCESS = 'GET_ACCOUNT_DETAILS_SUCCESS';

export const SAVE_ACCOUNT_DETAILS = 'SAVE_ACCOUNT_DETAILS';

export const TOGGLE_EDIT_VISIBILITY = 'TOGGLE_EDIT_VISIBILITY';

export const GET_MEMBERSHIP = 'GET_MEMBERSHIP';
export const GET_MEMBERSHIP_SUCCESS = 'GET_MEMBERSHIP_SUCCESS';
export const UPDATE_MEMBERSHIP_SUCCESS = 'UPDATE_MEMBERSHIP_SUCCESS';
export const UPDATE_FEATURE_FLAGS = 'UPDATE_FEATURE_FLAGS';