export const GET_ACCOUNT_DETAILS = 'GET_ACCOUNT_DETAILS';
export const GET_ACCOUNT_DETAILS_SUCCESS = 'GET_ACCOUNT_DETAILS_SUCCESS';

export const SAVE_ACCOUNT_DETAILS = 'SAVE_ACCOUNT_DETAILS';

export const TOGGLE_EDIT_VISIBILITY = 'TOGGLE_EDIT_VISIBILITY';