export const timezones = [
    { value: "Pacific/Tongatapu", text: "(GMT+13:00) Nukualofa" },
    { value: "Pacific/Fiji", text: "(GMT+12:00) Fiji, Kamchatka, Marshall Is." },
    { value: "Pacific/Auckland", text: "(GMT+12:00) Auckland, Wellington" },
    { value: "Asia/Magadan", text: "(GMT+11:00) Magadan, Solomon Is., New Caledonia" },
    { value: "Asia/Vladivostok", text: "(GMT+10:00) Vladivostok" },
    { value: "Australia/Hobart", text: "(GMT+10:00) Hobart" },
    { value: "Pacific/Guam", text: "(GMT+10:00) Guam, Port Moresby" },
    { value: "Australia/Sydney", text: "(GMT+10:00) Canberra, Melbourne, Sydney" },
    { value: "Australia/Brisbane", text: "(GMT+10:00) Brisbane" },
    { value: "Australia/Adelaide", text: "(GMT+09:30) Adelaide" },
    { value: "Asia/Yakutsk", text: "(GMT+09:00) Yakutsk" },
    { value: "Asia/Seoul", text: "(GMT+09:00) Seoul" },
    { value: "Asia/Tokyo", text: "(GMT+09:00) Osaka, Sapporo, Tokyo" },
    { value: "Asia/Taipei", text: "(GMT+08:00) Taipei" },
    { value: "Australia/Perth", text: "(GMT+08:00) Perth" },
    { value: "Asia/Kuala_Lumpur", text: "(GMT+08:00) Kuala Lumpur, Singapore" },
    { value: "Asia/Irkutsk", text: "(GMT+08:00) Irkutsk, Ulaan Bataar" },
    { value: "Asia/Hong_Kong", text: "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi" },
    { value: "Asia/Krasnoyarsk", text: "(GMT+07:00) Krasnoyarsk" },
    { value: "Asia/Bangkok", text: "(GMT+07:00) Bangkok, Hanoi, Jakarta" },
    { value: "Asia/Rangoon", text: "(GMT+06:30) Rangoon" },
    { value: "Asia/Dhaka", text: "(GMT+06:00) Astana, Dhaka" },
    { value: "Asia/Almaty", text: "(GMT+06:00) Almaty, Novosibirsk" },
    { value: "Asia/Katmandu", text: "(GMT+05:45) Kathmandu" },
    { value: "Asia/Colombo", text: "(GMT+05:30) Sri Jayawardenepura" },
    { value: "Asia/Calcutta", text: "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi" },
    { value: "Asia/Karachi", text: "(GMT+05:00) Islamabad, Karachi, Tashkent" },
    { value: "Asia/Yekaterinburg", text: "(GMT+05:00) Ekaterinburg" },
    { value: "Asia/Kabul", text: "(GMT+04:30) Kabul" },
    { value: "Asia/Baku", text: "(GMT+04:00) Baku, Tbilisi, Yerevan" },
    { value: "Asia/Dubai", text: "(GMT+04:00) Abu Dhabi, Muscat" },
    { value: "Asia/Tehran", text: "(GMT+03:30) Tehran" },
    { value: "Africa/Nairobi", text: "(GMT+03:00) Nairobi" },
    { value: "Europe/Moscow", text: "(GMT+03:00) Moscow, St. Petersburg, Volgograd" },
    { value: "Asia/Kuwait", text: "(GMT+03:00) Kuwait, Riyadh" },
    { value: "Asia/Baghdad", text: "(GMT+03:00) Baghdad" },
    { value: "Asia/Jerusalem", text: "(GMT+02:00) Jerusalem" },
    { value: "Europe/Helsinki", text: "(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius" },
    { value: "Africa/Harare", text: "(GMT+02:00) Harare, Pretoria" },
    { value: "Africa/Cairo", text: "(GMT+02:00) Cairo" },
    { value: "Europe/Bucharest", text: "(GMT+02:00) Bucharest" },
    { value: "Europe/Athens", text: "(GMT+02:00) Athens, Istanbul, Minsk" },
    { value: "Africa/Lagos", text: "(GMT+01:00) West Central Africa" },
    { value: "Europe/Warsaw", text: "(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb" },
    { value: "Europe/Brussels", text: "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris" },
    { value: "Europe/Belgrade", text: "(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, PraguePrague" },
    { value: "Europe/Amsterdam", text: "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" },
    { value: "Africa/Casablanca", text: "(GMT+00:00) Casablanca, Monrovia" },
    { value: "Europe/Dublin", text: "(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, LondonLondon" },
    { value: "Atlantic/Azores", text: "(GMT-01:00) Azores" },
    { value: "Atlantic/Cape_Verde", text: "(GMT-01:00) Cape Verde Is." },
    { value: "Atlantic/South_Georgia", text: "(GMT-02:00) Mid-Atlantic" },
    { value: "America/Sao_Paulo", text: "(GMT-03:00) Brasilia" },
    { value: "America/Buenos_Aires", text: "(GMT-03:00) Buenos Aires, Georgetown" },
    { value: "America/St_Johns", text: "(GMT-03:30) Newfoundland" },
    { value: "America/Thule", text: "(GMT-04:00) Greenland" },
    { value: "America/La_Paz", text: "(GMT-04:00) La Paz" },
    { value: "America/Santiago", text: "(GMT-04:00) Santiago" },
    { value: "America/Caracas", text: "(GMT-04:30) Caracas" },
    { value: "America/Bogota", text: "(GMT-05:00) Bogota, Lima, Quito" },
    { value: "America/New_York", text: "(GMT-05:00) Eastern Time (US & Canada)" },
    { value: "America/Indianapolis", text: "(GMT-05:00) Indiana East" },
    { value: "America/Montreal", text: "(GMT-05:00) Atlantic Time (Canada)" },
    { value: "America/Costa_Rica", text: "(GMT-06:00) Central America" },
    { value: "America/Chicago", text: "(GMT-06:00) Central Time (US & Canada)" },
    { value: "America/Mexico_City", text: "(GMT-06:00) Guadalajara, Mexico City, Monterrey" },
    { value: "America/Winnipeg", text: "(GMT-06:00) Saskatchewan" },
    { value: "America/Tegucigalpa", text: "(GMT-06:00) Chihuahua, La Paz, Mazatlan" },
    { value: "America/Phoenix", text: "(GMT-07:00) Arizona" },
    { value: "America/Denver", text: "(GMT-07:00) Mountain Time (US & Canada)" },
    { value: "America/Los_Angeles", text: "(GMT-08:00) Pacific Time (US & Canada) Tijuana" },
    { value: "America/Anchorage", text: "(GMT-09:00) Alaska" },
    { value: "Pacific/Honolulu", text: "(GMT-10:00) Hawaii" },
    { value: "Pacific/Apia", text: "(GMT-11:00) Midway Island, Samoa" },
    { value: "MIT", text: "(GMT-11:00) International Date Line West" },
];